### PR TITLE
Atom crash bug

### PR DESCRIPTION
**Pull request by moxley**
This is an issue related to this package that is causing Atom to crash for my environment. Since GitHub Issues are not available for this project, I created a PR to describe the issue. See the committed file for details.

### CODE REVIEW

**Comment by tommyc325** [comment]
Agreed - I am having the same exact issue,

**Comment by clamentsanz** [comment]
I have the same issue...

**Comment by surfdawg** [comment]
I am having the same problem while teaching a class room full of kids. On Windows and Mac OS both... I can provide more details if needed on how to re-create...

**Comment by surfdawg** [comment]
To reproduce the issue, open the following file in Atom. Save as index.html.
Open atom-html-preview.
Start changing some value in the css section, such as margin-left and margin-right, to 200px or 300px.
You can also get it to crash if you change the .profile header img { height to 200, 300 autopx;
You can also get it to crash if you change the .profile .examples canvas { width and height to 200, 300px.

[index.html.zip](https://github.com/harmsk/atom-html-preview/files/1454844/index.html.zip)
Thanks,
Craig

**Comment by harmsk** [comment]
@surfdawg Thanks for the example. 

I've tried to reproduce this. I cannot. Atom is not crashing the live preview. It's working as I change the CSS.

Fedora 26 x64.
Atom 1.22.0 x64
html-preview 0.2.2

**Comment by surfdawg** [comment]
@harmsk 
So I thought maybe it was the atom version. I downloaded 1.22.0 x64 and the same thing happens.
This time I was able to reproduce it by changing the ../monster.png to monster1.png and monster2.png. Then I did a CTRL-SHIFT-H a couple of times.
Attached is the bug report from the MAC.

Have you tried is on a MAC OS X?
Thanks.
[atom-html-preview-bug-report.txt.zip](https://github.com/harmsk/atom-html-preview/files/1455552/atom-html-preview-bug-report.txt.zip)

**Comment by tommyc325** [comment]
My issue is happening on OSX

**Comment by harmsk** [comment]
#159

**Pull request closed without merging**
